// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPersonalID holds the string denoting the personalid field in the database.
	FieldPersonalID = "personal_id"
	// FieldPersonalName holds the string denoting the personalname field in the database.
	FieldPersonalName = "personal_name"

	// EdgeFaculty holds the string denoting the faculty edge name in mutations.
	EdgeFaculty = "faculty"
	// EdgeBranch holds the string denoting the branch edge name in mutations.
	EdgeBranch = "branch"
	// EdgeBuilding holds the string denoting the building edge name in mutations.
	EdgeBuilding = "building"
	// EdgeRoom holds the string denoting the room edge name in mutations.
	EdgeRoom = "room"

	// Table holds the table name of the user in the database.
	Table = "users"
	// FacultyTable is the table the holds the faculty relation/edge.
	FacultyTable = "users"
	// FacultyInverseTable is the table name for the Faculty entity.
	// It exists in this package in order to avoid circular dependency with the "faculty" package.
	FacultyInverseTable = "faculties"
	// FacultyColumn is the table column denoting the faculty relation/edge.
	FacultyColumn = "faculty_id"
	// BranchTable is the table the holds the branch relation/edge.
	BranchTable = "users"
	// BranchInverseTable is the table name for the Branch entity.
	// It exists in this package in order to avoid circular dependency with the "branch" package.
	BranchInverseTable = "branches"
	// BranchColumn is the table column denoting the branch relation/edge.
	BranchColumn = "branch_id"
	// BuildingTable is the table the holds the building relation/edge.
	BuildingTable = "users"
	// BuildingInverseTable is the table name for the Building entity.
	// It exists in this package in order to avoid circular dependency with the "building" package.
	BuildingInverseTable = "buildings"
	// BuildingColumn is the table column denoting the building relation/edge.
	BuildingColumn = "building_id"
	// RoomTable is the table the holds the room relation/edge.
	RoomTable = "users"
	// RoomInverseTable is the table name for the Room entity.
	// It exists in this package in order to avoid circular dependency with the "room" package.
	RoomInverseTable = "rooms"
	// RoomColumn is the table column denoting the room relation/edge.
	RoomColumn = "room_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldPersonalID,
	FieldPersonalName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the User type.
var ForeignKeys = []string{
	"branch_id",
	"building_id",
	"faculty_id",
	"room_id",
}
