// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Branch is the predicate function for branch builders.
type Branch func(*sql.Selector)

// Building is the predicate function for building builders.
type Building func(*sql.Selector)

// Faculty is the predicate function for faculty builders.
type Faculty func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
