// Code generated by entc, DO NOT EDIT.

package employee

const (
	// Label holds the string label denoting the employee type in the database.
	Label = "employee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmployeeEmail holds the string denoting the employeeemail field in the database.
	FieldEmployeeEmail = "employee_email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"

	// Table holds the table name of the employee in the database.
	Table = "employees"
)

// Columns holds all SQL columns for employee fields.
var Columns = []string{
	FieldID,
	FieldEmployeeEmail,
	FieldPassword,
}
