// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/moominzie/user-record/ent/building"
	"github.com/moominzie/user-record/ent/user"
)

// BuildingCreate is the builder for creating a Building entity.
type BuildingCreate struct {
	config
	mutation *BuildingMutation
	hooks    []Hook
}

// SetBuname sets the buname field.
func (bc *BuildingCreate) SetBuname(s string) *BuildingCreate {
	bc.mutation.SetBuname(s)
	return bc
}

// AddUserInformationIDs adds the user_informations edge to User by ids.
func (bc *BuildingCreate) AddUserInformationIDs(ids ...int) *BuildingCreate {
	bc.mutation.AddUserInformationIDs(ids...)
	return bc
}

// AddUserInformations adds the user_informations edges to User.
func (bc *BuildingCreate) AddUserInformations(u ...*User) *BuildingCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return bc.AddUserInformationIDs(ids...)
}

// Mutation returns the BuildingMutation object of the builder.
func (bc *BuildingCreate) Mutation() *BuildingMutation {
	return bc.mutation
}

// Save creates the Building in the database.
func (bc *BuildingCreate) Save(ctx context.Context) (*Building, error) {
	if _, ok := bc.mutation.Buname(); !ok {
		return nil, &ValidationError{Name: "buname", err: errors.New("ent: missing required field \"buname\"")}
	}
	var (
		err  error
		node *Building
	)
	if len(bc.hooks) == 0 {
		node, err = bc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BuildingMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bc.mutation = mutation
			node, err = bc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(bc.hooks) - 1; i >= 0; i-- {
			mut = bc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BuildingCreate) SaveX(ctx context.Context) *Building {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bc *BuildingCreate) sqlSave(ctx context.Context) (*Building, error) {
	b, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	b.ID = int(id)
	return b, nil
}

func (bc *BuildingCreate) createSpec() (*Building, *sqlgraph.CreateSpec) {
	var (
		b     = &Building{config: bc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: building.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: building.FieldID,
			},
		}
	)
	if value, ok := bc.mutation.Buname(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: building.FieldBuname,
		})
		b.Buname = value
	}
	if nodes := bc.mutation.UserInformationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   building.UserInformationsTable,
			Columns: []string{building.UserInformationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return b, _spec
}
