// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/moominzie/user-record/ent/faculty"
	"github.com/moominzie/user-record/ent/predicate"
	"github.com/moominzie/user-record/ent/user"
)

// FacultyUpdate is the builder for updating Faculty entities.
type FacultyUpdate struct {
	config
	hooks      []Hook
	mutation   *FacultyMutation
	predicates []predicate.Faculty
}

// Where adds a new predicate for the builder.
func (fu *FacultyUpdate) Where(ps ...predicate.Faculty) *FacultyUpdate {
	fu.predicates = append(fu.predicates, ps...)
	return fu
}

// SetFname sets the fname field.
func (fu *FacultyUpdate) SetFname(s string) *FacultyUpdate {
	fu.mutation.SetFname(s)
	return fu
}

// AddUserInformationIDs adds the user_informations edge to User by ids.
func (fu *FacultyUpdate) AddUserInformationIDs(ids ...int) *FacultyUpdate {
	fu.mutation.AddUserInformationIDs(ids...)
	return fu
}

// AddUserInformations adds the user_informations edges to User.
func (fu *FacultyUpdate) AddUserInformations(u ...*User) *FacultyUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return fu.AddUserInformationIDs(ids...)
}

// Mutation returns the FacultyMutation object of the builder.
func (fu *FacultyUpdate) Mutation() *FacultyMutation {
	return fu.mutation
}

// RemoveUserInformationIDs removes the user_informations edge to User by ids.
func (fu *FacultyUpdate) RemoveUserInformationIDs(ids ...int) *FacultyUpdate {
	fu.mutation.RemoveUserInformationIDs(ids...)
	return fu
}

// RemoveUserInformations removes user_informations edges to User.
func (fu *FacultyUpdate) RemoveUserInformations(u ...*User) *FacultyUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return fu.RemoveUserInformationIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (fu *FacultyUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(fu.hooks) == 0 {
		affected, err = fu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FacultyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fu.mutation = mutation
			affected, err = fu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(fu.hooks) - 1; i >= 0; i-- {
			mut = fu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FacultyUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FacultyUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FacultyUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fu *FacultyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   faculty.Table,
			Columns: faculty.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: faculty.FieldID,
			},
		},
	}
	if ps := fu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.Fname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: faculty.FieldFname,
		})
	}
	if nodes := fu.mutation.RemovedUserInformationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   faculty.UserInformationsTable,
			Columns: []string{faculty.UserInformationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.UserInformationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   faculty.UserInformationsTable,
			Columns: []string{faculty.UserInformationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{faculty.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// FacultyUpdateOne is the builder for updating a single Faculty entity.
type FacultyUpdateOne struct {
	config
	hooks    []Hook
	mutation *FacultyMutation
}

// SetFname sets the fname field.
func (fuo *FacultyUpdateOne) SetFname(s string) *FacultyUpdateOne {
	fuo.mutation.SetFname(s)
	return fuo
}

// AddUserInformationIDs adds the user_informations edge to User by ids.
func (fuo *FacultyUpdateOne) AddUserInformationIDs(ids ...int) *FacultyUpdateOne {
	fuo.mutation.AddUserInformationIDs(ids...)
	return fuo
}

// AddUserInformations adds the user_informations edges to User.
func (fuo *FacultyUpdateOne) AddUserInformations(u ...*User) *FacultyUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return fuo.AddUserInformationIDs(ids...)
}

// Mutation returns the FacultyMutation object of the builder.
func (fuo *FacultyUpdateOne) Mutation() *FacultyMutation {
	return fuo.mutation
}

// RemoveUserInformationIDs removes the user_informations edge to User by ids.
func (fuo *FacultyUpdateOne) RemoveUserInformationIDs(ids ...int) *FacultyUpdateOne {
	fuo.mutation.RemoveUserInformationIDs(ids...)
	return fuo
}

// RemoveUserInformations removes user_informations edges to User.
func (fuo *FacultyUpdateOne) RemoveUserInformations(u ...*User) *FacultyUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return fuo.RemoveUserInformationIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (fuo *FacultyUpdateOne) Save(ctx context.Context) (*Faculty, error) {

	var (
		err  error
		node *Faculty
	)
	if len(fuo.hooks) == 0 {
		node, err = fuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FacultyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fuo.mutation = mutation
			node, err = fuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(fuo.hooks) - 1; i >= 0; i-- {
			mut = fuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FacultyUpdateOne) SaveX(ctx context.Context) *Faculty {
	f, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return f
}

// Exec executes the query on the entity.
func (fuo *FacultyUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FacultyUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fuo *FacultyUpdateOne) sqlSave(ctx context.Context) (f *Faculty, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   faculty.Table,
			Columns: faculty.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: faculty.FieldID,
			},
		},
	}
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Faculty.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := fuo.mutation.Fname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: faculty.FieldFname,
		})
	}
	if nodes := fuo.mutation.RemovedUserInformationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   faculty.UserInformationsTable,
			Columns: []string{faculty.UserInformationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.UserInformationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   faculty.UserInformationsTable,
			Columns: []string{faculty.UserInformationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	f = &Faculty{config: fuo.config}
	_spec.Assign = f.assignValues
	_spec.ScanValues = f.scanValues()
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{faculty.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return f, nil
}
