// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/moominzie/user-record/ent/faculty"
)

// Faculty is the model entity for the Faculty schema.
type Faculty struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Fname holds the value of the "fname" field.
	Fname string `json:"fname,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FacultyQuery when eager-loading is set.
	Edges FacultyEdges `json:"edges"`
}

// FacultyEdges holds the relations/edges for other nodes in the graph.
type FacultyEdges struct {
	// UserInformations holds the value of the user_informations edge.
	UserInformations []*User
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserInformationsOrErr returns the UserInformations value or an error if the edge
// was not loaded in eager-loading.
func (e FacultyEdges) UserInformationsOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.UserInformations, nil
	}
	return nil, &NotLoadedError{edge: "user_informations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Faculty) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // fname
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Faculty fields.
func (f *Faculty) assignValues(values ...interface{}) error {
	if m, n := len(values), len(faculty.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	f.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field fname", values[0])
	} else if value.Valid {
		f.Fname = value.String
	}
	return nil
}

// QueryUserInformations queries the user_informations edge of the Faculty.
func (f *Faculty) QueryUserInformations() *UserQuery {
	return (&FacultyClient{config: f.config}).QueryUserInformations(f)
}

// Update returns a builder for updating this Faculty.
// Note that, you need to call Faculty.Unwrap() before calling this method, if this Faculty
// was returned from a transaction, and the transaction was committed or rolled back.
func (f *Faculty) Update() *FacultyUpdateOne {
	return (&FacultyClient{config: f.config}).UpdateOne(f)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (f *Faculty) Unwrap() *Faculty {
	tx, ok := f.config.driver.(*txDriver)
	if !ok {
		panic("ent: Faculty is not a transactional entity")
	}
	f.config.driver = tx.drv
	return f
}

// String implements the fmt.Stringer.
func (f *Faculty) String() string {
	var builder strings.Builder
	builder.WriteString("Faculty(")
	builder.WriteString(fmt.Sprintf("id=%v", f.ID))
	builder.WriteString(", fname=")
	builder.WriteString(f.Fname)
	builder.WriteByte(')')
	return builder.String()
}

// Faculties is a parsable slice of Faculty.
type Faculties []*Faculty

func (f Faculties) config(cfg config) {
	for _i := range f {
		f[_i].config = cfg
	}
}
