// Code generated by entc, DO NOT EDIT.

package building

const (
	// Label holds the string label denoting the building type in the database.
	Label = "building"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBuname holds the string denoting the buname field in the database.
	FieldBuname = "buname"

	// EdgeUserInformations holds the string denoting the user_informations edge name in mutations.
	EdgeUserInformations = "user_informations"

	// Table holds the table name of the building in the database.
	Table = "buildings"
	// UserInformationsTable is the table the holds the user_informations relation/edge.
	UserInformationsTable = "users"
	// UserInformationsInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInformationsInverseTable = "users"
	// UserInformationsColumn is the table column denoting the user_informations relation/edge.
	UserInformationsColumn = "building_id"
)

// Columns holds all SQL columns for building fields.
var Columns = []string{
	FieldID,
	FieldBuname,
}
