// Code generated by entc, DO NOT EDIT.

package building

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/moominzie/user-record/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Buname applies equality check predicate on the "buname" field. It's identical to BunameEQ.
func Buname(v string) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBuname), v))
	})
}

// BunameEQ applies the EQ predicate on the "buname" field.
func BunameEQ(v string) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldBuname), v))
	})
}

// BunameNEQ applies the NEQ predicate on the "buname" field.
func BunameNEQ(v string) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldBuname), v))
	})
}

// BunameIn applies the In predicate on the "buname" field.
func BunameIn(vs ...string) predicate.Building {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Building(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldBuname), v...))
	})
}

// BunameNotIn applies the NotIn predicate on the "buname" field.
func BunameNotIn(vs ...string) predicate.Building {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Building(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldBuname), v...))
	})
}

// BunameGT applies the GT predicate on the "buname" field.
func BunameGT(v string) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldBuname), v))
	})
}

// BunameGTE applies the GTE predicate on the "buname" field.
func BunameGTE(v string) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldBuname), v))
	})
}

// BunameLT applies the LT predicate on the "buname" field.
func BunameLT(v string) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldBuname), v))
	})
}

// BunameLTE applies the LTE predicate on the "buname" field.
func BunameLTE(v string) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldBuname), v))
	})
}

// BunameContains applies the Contains predicate on the "buname" field.
func BunameContains(v string) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldBuname), v))
	})
}

// BunameHasPrefix applies the HasPrefix predicate on the "buname" field.
func BunameHasPrefix(v string) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldBuname), v))
	})
}

// BunameHasSuffix applies the HasSuffix predicate on the "buname" field.
func BunameHasSuffix(v string) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldBuname), v))
	})
}

// BunameEqualFold applies the EqualFold predicate on the "buname" field.
func BunameEqualFold(v string) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldBuname), v))
	})
}

// BunameContainsFold applies the ContainsFold predicate on the "buname" field.
func BunameContainsFold(v string) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldBuname), v))
	})
}

// HasUserInformations applies the HasEdge predicate on the "user_informations" edge.
func HasUserInformations() predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInformationsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserInformationsTable, UserInformationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserInformationsWith applies the HasEdge predicate on the "user_informations" edge with a given conditions (other predicates).
func HasUserInformationsWith(preds ...predicate.User) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInformationsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserInformationsTable, UserInformationsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Building) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Building) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Building) predicate.Building {
	return predicate.Building(func(s *sql.Selector) {
		p(s.Not())
	})
}
