// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// BranchesColumns holds the columns for the "branches" table.
	BranchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "brname", Type: field.TypeString, Unique: true},
	}
	// BranchesTable holds the schema information for the "branches" table.
	BranchesTable = &schema.Table{
		Name:        "branches",
		Columns:     BranchesColumns,
		PrimaryKey:  []*schema.Column{BranchesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// BuildingsColumns holds the columns for the "buildings" table.
	BuildingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "buname", Type: field.TypeString, Unique: true},
	}
	// BuildingsTable holds the schema information for the "buildings" table.
	BuildingsTable = &schema.Table{
		Name:        "buildings",
		Columns:     BuildingsColumns,
		PrimaryKey:  []*schema.Column{BuildingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// FacultiesColumns holds the columns for the "faculties" table.
	FacultiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "fname", Type: field.TypeString, Unique: true},
	}
	// FacultiesTable holds the schema information for the "faculties" table.
	FacultiesTable = &schema.Table{
		Name:        "faculties",
		Columns:     FacultiesColumns,
		PrimaryKey:  []*schema.Column{FacultiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// RoomsColumns holds the columns for the "rooms" table.
	RoomsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "rname", Type: field.TypeString, Unique: true},
	}
	// RoomsTable holds the schema information for the "rooms" table.
	RoomsTable = &schema.Table{
		Name:        "rooms",
		Columns:     RoomsColumns,
		PrimaryKey:  []*schema.Column{RoomsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "personal_id", Type: field.TypeString, Unique: true},
		{Name: "personal_name", Type: field.TypeString},
		{Name: "branch_id", Type: field.TypeInt, Nullable: true},
		{Name: "building_id", Type: field.TypeInt, Nullable: true},
		{Name: "faculty_id", Type: field.TypeInt, Nullable: true},
		{Name: "room_id", Type: field.TypeInt, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "users_branches_user_informations",
				Columns: []*schema.Column{UsersColumns[3]},

				RefColumns: []*schema.Column{BranchesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "users_buildings_user_informations",
				Columns: []*schema.Column{UsersColumns[4]},

				RefColumns: []*schema.Column{BuildingsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "users_faculties_user_informations",
				Columns: []*schema.Column{UsersColumns[5]},

				RefColumns: []*schema.Column{FacultiesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "users_rooms_user_informations",
				Columns: []*schema.Column{UsersColumns[6]},

				RefColumns: []*schema.Column{RoomsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BranchesTable,
		BuildingsTable,
		FacultiesTable,
		RoomsTable,
		UsersTable,
	}
)

func init() {
	UsersTable.ForeignKeys[0].RefTable = BranchesTable
	UsersTable.ForeignKeys[1].RefTable = BuildingsTable
	UsersTable.ForeignKeys[2].RefTable = FacultiesTable
	UsersTable.ForeignKeys[3].RefTable = RoomsTable
}
