/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBranchEdges,
    EntBranchEdgesFromJSON,
    EntBranchEdgesFromJSONTyped,
    EntBranchEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBranch
 */
export interface EntBranch {
    /**
     * Brname holds the value of the "brname" field.
     * @type {string}
     * @memberof EntBranch
     */
    brname?: string;
    /**
     * 
     * @type {EntBranchEdges}
     * @memberof EntBranch
     */
    edges?: EntBranchEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntBranch
     */
    id?: number;
}

export function EntBranchFromJSON(json: any): EntBranch {
    return EntBranchFromJSONTyped(json, false);
}

export function EntBranchFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBranch {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'brname': !exists(json, 'brname') ? undefined : json['brname'],
        'edges': !exists(json, 'edges') ? undefined : EntBranchEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntBranchToJSON(value?: EntBranch | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'brname': value.brname,
        'edges': EntBranchEdgesToJSON(value.edges),
        'id': value.id,
    };
}


