/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBranch,
    EntBranchFromJSON,
    EntBranchFromJSONTyped,
    EntBranchToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntFacultyEdges
 */
export interface EntFacultyEdges {
    /**
     * Branchs holds the value of the branchs edge.
     * @type {Array<EntBranch>}
     * @memberof EntFacultyEdges
     */
    branchs?: Array<EntBranch>;
    /**
     * UserInformations holds the value of the user_informations edge.
     * @type {Array<EntUser>}
     * @memberof EntFacultyEdges
     */
    userInformations?: Array<EntUser>;
}

export function EntFacultyEdgesFromJSON(json: any): EntFacultyEdges {
    return EntFacultyEdgesFromJSONTyped(json, false);
}

export function EntFacultyEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntFacultyEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'branchs': !exists(json, 'branchs') ? undefined : ((json['branchs'] as Array<any>).map(EntBranchFromJSON)),
        'userInformations': !exists(json, 'userInformations') ? undefined : ((json['userInformations'] as Array<any>).map(EntUserFromJSON)),
    };
}

export function EntFacultyEdgesToJSON(value?: EntFacultyEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'branchs': value.branchs === undefined ? undefined : ((value.branchs as Array<any>).map(EntBranchToJSON)),
        'userInformations': value.userInformations === undefined ? undefined : ((value.userInformations as Array<any>).map(EntUserToJSON)),
    };
}


