/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBuilding,
    EntBuildingFromJSON,
    EntBuildingFromJSONTyped,
    EntBuildingToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRoomEdges
 */
export interface EntRoomEdges {
    /**
     * 
     * @type {EntBuilding}
     * @memberof EntRoomEdges
     */
    building?: EntBuilding;
    /**
     * UserInformations holds the value of the user_informations edge.
     * @type {Array<EntUser>}
     * @memberof EntRoomEdges
     */
    userInformations?: Array<EntUser>;
}

export function EntRoomEdgesFromJSON(json: any): EntRoomEdges {
    return EntRoomEdgesFromJSONTyped(json, false);
}

export function EntRoomEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRoomEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'building': !exists(json, 'building') ? undefined : EntBuildingFromJSON(json['building']),
        'userInformations': !exists(json, 'userInformations') ? undefined : ((json['userInformations'] as Array<any>).map(EntUserFromJSON)),
    };
}

export function EntRoomEdgesToJSON(value?: EntRoomEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'building': EntBuildingToJSON(value.building),
        'userInformations': value.userInformations === undefined ? undefined : ((value.userInformations as Array<any>).map(EntUserToJSON)),
    };
}


