// Code generated by entc, DO NOT EDIT.

package room

const (
	// Label holds the string label denoting the room type in the database.
	Label = "room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRname holds the string denoting the rname field in the database.
	FieldRname = "rname"

	// EdgeUserInformations holds the string denoting the user_informations edge name in mutations.
	EdgeUserInformations = "user_informations"

	// Table holds the table name of the room in the database.
	Table = "rooms"
	// UserInformationsTable is the table the holds the user_informations relation/edge.
	UserInformationsTable = "users"
	// UserInformationsInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInformationsInverseTable = "users"
	// UserInformationsColumn is the table column denoting the user_informations relation/edge.
	UserInformationsColumn = "room_id"
)

// Columns holds all SQL columns for room fields.
var Columns = []string{
	FieldID,
	FieldRname,
}
